// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jasjrbplyqvwngescmql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphc2pyYnBseXF2d25nZXNjbXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODU2NzYsImV4cCI6MjA2NTE2MTY3Nn0.alMy5dJ3eE9K2ofLVz2NW46lA17ByoeHROFB6Jtln8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);